/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;
/**
 *
 * @author dhamara
 */
public class menu_utama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu_utama.class.getName());

    /**
     * Creates new form menu_utama
     */
    public menu_utama(String nama) {
        initComponents();
        lbl_nama.setText(nama);
        java.util.Date tgl = new java.util.Date();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
        lbl_tgl.setText(sdf.format(tgl)); // Ganti lbl_tanggal sesuai Variable Name kamu
    }
    
    public void tampil_stok() {
    try {
        java.sql.Connection conn = new koneksi().connect();
        
        // 1. Hitung total perangkat
        java.sql.Statement stm1 = conn.createStatement();
        java.sql.ResultSet res1 = stm1.executeQuery("SELECT COUNT(*) FROM perangkat");
        if (res1.next()) {
            lbl_stock_perangkat.setText(res1.getString(1) + " Items");
        }

        // 2. Hitung total kabel
        java.sql.Statement stm2 = conn.createStatement();
        java.sql.ResultSet res2 = stm2.executeQuery("SELECT COUNT(*) FROM kabel");
        if (res2.next()) {
            lbl_stock_kabel.setText(res2.getString(1) + " Rolls");
        }
        
    } catch (Exception e) {
        System.out.println("Error hitung stok: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tgl = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_stock_kabel = new javax.swing.JLabel();
        lbl_stock_perangkat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_tgl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuPerangkat = new javax.swing.JMenuItem();
        menuKabel = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuBarangMasuk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tgl.setText("Tanggal");
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        lbl_nama.setText("[nama user]");
        getContentPane().add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 220, 20));

        jLabel3.setText("Selamat Datang,");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lbl_stock.setText("Ringkasan Stock");
        getContentPane().add(lbl_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel2.setText("SISTEM APLIKASI INFORMASI STOK GUDANG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel5.setText("KELOMPOK 3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 79));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/dhamara/Downloads/Gudang-A2.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 261, 600, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/dhamara/Downloads/user.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/dhamara/Downloads/box.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 429, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/dhamara/Downloads/roll.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        lbl_stock_kabel.setText("[total item]");
        getContentPane().add(lbl_stock_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        lbl_stock_perangkat.setText("[total item]");
        getContentPane().add(lbl_stock_perangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/dhamara/Downloads/kalender.jpeg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        lbl_tgl.setText("[tgl hari ini]");
        getContentPane().add(lbl_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        jMenu1.setText("File");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(this::menuLogoutActionPerformed);
        jMenu1.add(menuLogout);

        menuExit.setText("Exit");
        menuExit.addActionListener(this::menuExitActionPerformed);
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Master Data");

        menuPerangkat.setText("Data Perangkat");
        menuPerangkat.addActionListener(this::menuPerangkatActionPerformed);
        jMenu3.add(menuPerangkat);

        menuKabel.setText("Data Kabel");
        menuKabel.addActionListener(this::menuKabelActionPerformed);
        jMenu3.add(menuKabel);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi");

        menuBarangMasuk.setText("jMenuItem1");
        jMenu4.add(menuBarangMasuk);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPerangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPerangkatActionPerformed
        // TODO add your handling code here:
        new barang().setVisible(true);
        
    }//GEN-LAST:event_menuPerangkatActionPerformed

    private void menuKabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKabelActionPerformed
        // TODO add your handling code here:
        new barang().setVisible(true);
    }//GEN-LAST:event_menuKabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu_utama("").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JLabel lbl_stock_kabel;
    private javax.swing.JLabel lbl_stock_perangkat;
    private javax.swing.JLabel lbl_tgl;
    private javax.swing.JMenuItem menuBarangMasuk;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuKabel;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPerangkat;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
