/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
/**
 *
 * @author dhamara
 */
public class barang extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(barang.class.getName());

    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
        datatable();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("SN Perangkat");
    model.addColumn("Nama Perangkat");
    model.addColumn("Jenis");
    model.addColumn("Dimensi");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery("SELECT * FROM Perangkat");
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_supplier.setModel(model); // Ganti tbl_barang sesuai nama variabel tabelmu
    } catch (Exception e) {
        System.out.println("Gagal load data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_dimensi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_router = new javax.swing.JRadioButton();
        rb_switch = new javax.swing.JRadioButton();
        rb_server = new javax.swing.JRadioButton();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supplier = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENGELOLAAN DATA PERANGKAT");

        jLabel2.setText("Serial Number ");

        txt_sn.addActionListener(this::txt_snActionPerformed);

        jLabel3.setText("Nama Perangkat");

        txt_dimensi.addActionListener(this::txt_dimensiActionPerformed);

        jLabel4.setText("Jenis Perangkat");

        txt_nama.addActionListener(this::txt_namaActionPerformed);

        jLabel5.setText("Dimensi");

        buttonGroup1.add(rb_router);
        rb_router.setText("Router");
        rb_router.addActionListener(this::rb_routerActionPerformed);

        buttonGroup1.add(rb_switch);
        rb_switch.setText("Switch");
        rb_switch.addActionListener(this::rb_switchActionPerformed);

        buttonGroup1.add(rb_server);
        rb_server.setText("Server");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_remove.setText("Remove");
        btn_remove.addActionListener(this::btn_removeActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        tbl_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_supplier);

        jLabel6.setText("Cari barang?");

        btn_cari.setText("cari");
        btn_cari.addActionListener(this::btn_cariActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_router)
                                .addGap(35, 35, 35)
                                .addComponent(rb_switch)
                                .addGap(33, 33, 33)
                                .addComponent(rb_server))
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dimensi, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_router)
                    .addComponent(rb_switch)
                    .addComponent(rb_server))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_dimensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_remove)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_snActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_snActionPerformed

    private void txt_dimensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dimensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dimensiActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void rb_routerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_routerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_routerActionPerformed

    private void rb_switchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_switchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_switchActionPerformed

// CRETE METHOD RESET untuk button batal
private void reset_form() {
    txt_sn.setText("");
    txt_nama.setText("");
    buttonGroup1.clearSelection();
    txt_dimensi.setText("");
    txt_sn.requestFocus();
}
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Ambil pilihan dari Radio Button
        String jenis = "";
        if (rb_router.isSelected()) { jenis = "Router"; }
        else if (rb_switch.isSelected()) { jenis = "Switch"; }
        else if (rb_server.isSelected()) { jenis = "Server"; }

    // 2. Query SQL (Urutan harus sama dengan kolom di database)
    String sql = "INSERT INTO Perangkat VALUES ('" 
                + txt_sn.getText() + "', '" 
                + txt_nama.getText() + "', '" 
                + jenis + "', '" 
                + txt_dimensi.getText() + "')";

                java.sql.Connection conn = new koneksi.koneksi().connect();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
    
    JOptionPane.showMessageDialog(null, "Data Perangkat Berhasil Disimpan!");
    
    // 3. Refresh tabel & bersihkan form
    datatable(); 
    reset_form();
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here
        reset_form();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tbl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_supplierMouseClicked
    // TODO add your handling code here:                                      
    int baris = tbl_supplier.getSelectedRow();
    
    // Mengambil data dari tabel ke TextField
    txt_sn.setText(tbl_supplier.getValueAt(baris, 0).toString());
    txt_nama.setText(tbl_supplier.getValueAt(baris, 1).toString());
    
    // Mengambil data untuk Radio Button (Jenis Perangkat)
    String jenis = tbl_supplier.getValueAt(baris, 2).toString();
    if(jenis.equals("Router")){
    rb_router.setSelected(true);
    } else if(jenis.equals("Switch")){
        rb_switch.setSelected(true);
    } else if(jenis.equals("Server")){
        rb_server.setSelected(true);
    }
    
    txt_dimensi.setText(tbl_supplier.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbl_supplierMouseClicked

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
            String sql = "DELETE FROM Perangkat WHERE sn_perangkat = '" + txt_sn.getText() + "'";
            java.sql.Connection conn = new koneksi.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            datatable();   // Refresh tabel
            reset_form();  // Kosongkan form
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
         }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
    // TODO add your handling code here:
        try {
        String jenis = "";
        if (rb_router.isSelected()) { jenis = "Router"; }
        else if (rb_switch.isSelected()) { jenis = "Switch"; }
        else if (rb_server.isSelected()) { jenis = "Server"; }

        String sql = "UPDATE Perangkat SET nama_perangkat=?, jenis_perangkat=?, Dimensi=? WHERE sn_perangkat=?";
    
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
        pst.setString(1, txt_nama.getText());
        pst.setString(2, jenis);
        pst.setString(3, txt_dimensi.getText());
        pst.setString(4, txt_sn.getText());
    
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        datatable();
        reset_form();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:                                      
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("SN Perangkat");
    model.addColumn("Nama Perangkat");
    model.addColumn("Jenis");
    model.addColumn("Dimensi");

    try {
        // Query menggunakan LIKE untuk mencari kata yang mengandung input dari txt_cari
        String sql = "SELECT * FROM Perangkat WHERE nama_perangkat LIKE '%" + txt_cari.getText() + "%' "
                   + "OR sn_perangkat LIKE '%" + txt_cari.getText() + "%'";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_supplier.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new barang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_router;
    private javax.swing.JRadioButton rb_server;
    private javax.swing.JRadioButton rb_switch;
    private javax.swing.JTable tbl_supplier;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_dimensi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_sn;
    // End of variables declaration//GEN-END:variables
}
