/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
/**
 *
 * @author dhamara
 */
public class clients extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(clients.class.getName());

    /**
     * Creates new form clients
     */
    public clients() {
        initComponents();
        datatable();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Client");
    model.addColumn("Nama Perusahaan");
    model.addColumn("Alamat Client");
    model.addColumn("No Telepon");
    model.addColumn("Nama PIC");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery("SELECT * FROM client");
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4),
                res.getString(5)
            });
        }
        tbl_clients.setModel(model); 
    } catch (Exception e) {
        System.out.println("Gagal load data: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid_clients = new javax.swing.JTextField();
        txtnm_perusahaan = new javax.swing.JTextField();
        txtalamat_client = new javax.swing.JTextField();
        txtnm_pic = new javax.swing.JTextField();
        txtno_telepon = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clients = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENGELOLAAN DATA CLIENTS");

        jLabel2.setText("ID Client");

        jLabel3.setText("Nama Perusahaan");

        jLabel4.setText("Alamat Client");

        jLabel5.setText("No Telepon");

        jLabel6.setText("Nama PIC");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_remove.setText("Remove");
        btn_remove.addActionListener(this::btn_removeActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        jLabel7.setText("Cari Data CLiens?");

        btn_cari.setText("Cari");
        btn_cari.addActionListener(this::btn_cariActionPerformed);

        tbl_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_clients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtid_clients)
                                    .addComponent(txtnm_perusahaan)
                                    .addComponent(txtalamat_client, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtnm_pic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtno_telepon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_cari))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(82, 82, 82)
                                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(31, 31, 31)
                                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid_clients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnm_perusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnm_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtno_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_remove)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void reset_form() {
    txtid_clients.setText("");
    txtnm_perusahaan.setText("");
    txtalamat_client.setText("");
    txtnm_pic.setText("");
    txtno_telepon.setText("");
    // Kembalikan ID agar bisa diisi lagi
    txtid_clients.setEditable(true);
    txtid_clients.requestFocus();
}
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO client VALUES ('" + txtid_clients.getText() + "','" 
                     + txtnm_perusahaan.getText() + "','" + txtalamat_client.getText() + "','" 
                     + txtno_telepon.getText() + "','" + txtnm_pic.getText() + "')";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Data Clients Berhasil Disimpan");
        datatable();
        reset_form();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Simpan Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
            String sql = "DELETE FROM client WHERE id_client = '" + txtid_clients.getText() + "'";
            java.sql.Connection conn = new koneksi.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            datatable();   // Refresh tabel
            reset_form();  // Kosongkan form
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
         }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
          try {
        String sql = "UPDATE client SET nama_perusahaan=?, alamat_client=?, no_telepon=?, nama_PIC=? WHERE id_client=?";
    
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
        // Mengisi parameter sesuai urutan tanda tanya (?) di atas
        pst.setString(1, txtnm_perusahaan.getText());
        pst.setString(2, txtalamat_client.getText());
        pst.setString(3, txtno_telepon.getText());
        pst.setString(4, txtnm_pic.getText());
        pst.setString(5, txtid_clients.getText()); 
    
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Clients Berhasil Diubah");
        
        datatable();    // Memanggil fungsi tampil data agar tabel refresh
        reset_form();   // Memanggil fungsi kosongkan form agar inputan bersih
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit Data Clients: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientsMouseClicked
        // TODO add your handling code here:
         int baris = tbl_clients.getSelectedRow();
  
        txtid_clients.setText(tbl_clients.getValueAt(baris, 0).toString());
        txtnm_perusahaan.setText(tbl_clients.getValueAt(baris, 1).toString());
        txtalamat_client.setText(tbl_clients.getValueAt(baris, 2).toString());
        txtno_telepon.setText(tbl_clients.getValueAt(baris, 3).toString());
        txtnm_pic.setText(tbl_clients.getValueAt(baris, 4).toString());
    
        // 3. Kunci ID Supplier agar tidak bisa diubah saat proses edit
        txtid_clients.setEditable(false);
    }//GEN-LAST:event_tbl_clientsMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        reset_form();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah anda yakin ingin keluar dari Pengelolaan Data Client?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION);
    
    // Jika user klik tombol YES
    if (confirm == JOptionPane.YES_OPTION) {
        dispose(); // Menutup form Supplier saja
    }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Client");
    model.addColumn("Nama Perusahaan");
    model.addColumn("Alamat Client");
    model.addColumn("No Telepon");
    model.addColumn("Nama PIC");

    try {
        // Query menggunakan LIKE untuk mencari kata yang mengandung input dari txt_cari
        String sql = "SELECT * FROM Client WHERE nama_persahaan LIKE '%" + txtcari.getText() + "%' "
                   + "OR id_client LIKE '%" + txtcari.getText() + "%'";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_clients.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());   
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new clients().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_clients;
    private javax.swing.JTextField txtalamat_client;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid_clients;
    private javax.swing.JTextField txtnm_perusahaan;
    private javax.swing.JTextField txtnm_pic;
    private javax.swing.JTextField txtno_telepon;
    // End of variables declaration//GEN-END:variables
}
