/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
/**
 *
 * @author dhamara
 */
public class kabel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kabel.class.getName());

    /**
     * Creates new form barang
     */
    public kabel() {
        initComponents();
        datatable();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kabel");
    model.addColumn("Panjang Kabel");
    model.addColumn("Jenis");
    model.addColumn("Tipe Kabel");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery("SELECT * FROM Kabel");
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_kabel.setModel(model); // Ganti tbl_barang sesuai nama variabel tabelmu
    } catch (Exception e) {
        System.out.println("Gagal load data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tpkabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_pjgkabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_lan = new javax.swing.JRadioButton();
        rb_fo = new javax.swing.JRadioButton();
        rb_console = new javax.swing.JRadioButton();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENGELOLAAN DATA KABEL");

        jLabel2.setText("ID Kabel");

        txt_id.addActionListener(this::txt_idActionPerformed);

        jLabel3.setText("Panjang Kabel");

        txt_tpkabel.addActionListener(this::txt_tpkabelActionPerformed);

        jLabel4.setText("Jenis Kabel");

        txt_pjgkabel.addActionListener(this::txt_pjgkabelActionPerformed);

        jLabel5.setText("Tipe Kabel");

        buttonGroup1.add(rb_lan);
        rb_lan.setText("LAN");
        rb_lan.addActionListener(this::rb_lanActionPerformed);

        buttonGroup1.add(rb_fo);
        rb_fo.setText("FO");
        rb_fo.addActionListener(this::rb_foActionPerformed);

        buttonGroup1.add(rb_console);
        rb_console.setText("Console");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_remove.setText("Remove");
        btn_remove.addActionListener(this::btn_removeActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        tbl_kabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kabel);

        jLabel6.setText("Cari kabel?");

        btn_cari.setText("cari");
        btn_cari.addActionListener(this::btn_cariActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari)))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_lan)
                                .addGap(35, 35, 35)
                                .addComponent(rb_fo)
                                .addGap(33, 33, 33)
                                .addComponent(rb_console))
                            .addComponent(txt_pjgkabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tpkabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pjgkabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rb_lan)
                    .addComponent(rb_fo)
                    .addComponent(rb_console))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tpkabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_remove)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_pjgkabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pjgkabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pjgkabelActionPerformed

    private void rb_lanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_lanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_lanActionPerformed

    private void rb_foActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_foActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_foActionPerformed

// CRETE METHOD RESET untuk button batal
private void reset_form() {
    txt_id.setText("");
    txt_pjgkabel.setText("");
    buttonGroup1.clearSelection();
    txt_tpkabel.setText("");
    txt_id.requestFocus();
}
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        try {
    // 1. Ambil pilihan dari Radio Button
        String jenis = "";
        if (rb_lan.isSelected()) { jenis = "LAN"; }
        else if (rb_fo.isSelected()) { jenis = "FO"; }
        else if (rb_console.isSelected()) { jenis = "Console"; }

    // 2. Query SQL (Urutan harus sama dengan kolom di database)
    String sql = "INSERT INTO Kabel VALUES ('" 
                + txt_id.getText() + "', '" 
                + txt_pjgkabel.getText() + "', '" 
                + jenis + "', '" 
                + txt_tpkabel.getText() + "')";

                java.sql.Connection conn = new koneksi.koneksi().connect();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
    
    JOptionPane.showMessageDialog(null, "Data Kabel Berhasil Disimpan!");
    
    // 3. Refresh tabel & bersihkan form
    datatable(); 
    reset_form();
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here
        reset_form();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tbl_kabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kabelMouseClicked
    // TODO add your handling code here:                                      
    int baris = tbl_kabel.getSelectedRow();
    
    // Mengambil data dari tabel ke TextField
    txt_id.setText(tbl_kabel.getValueAt(baris, 0).toString());
    txt_pjgkabel.setText(tbl_kabel.getValueAt(baris, 1).toString());
    
    // Mengambil data untuk Radio Button (Jenis Perangkat)
    String jenis = tbl_kabel.getValueAt(baris, 2).toString();
    if(jenis.equals("LAN")){
    rb_lan.setSelected(true);
    } else if(jenis.equals("FO")){
        rb_fo.setSelected(true);
    } else if(jenis.equals("Console")){
        rb_console.setSelected(true);
    }
    
    txt_tpkabel.setText(tbl_kabel.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tbl_kabelMouseClicked

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
            String sql = "DELETE FROM Kabel WHERE id_kabel = '" + txt_id.getText() + "'";
            java.sql.Connection conn = new koneksi.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            datatable();   // Refresh tabel
            reset_form();  // Kosongkan form
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
         }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
    // TODO add your handling code here:
        try {
        String jenis = "";
        if (rb_lan.isSelected()) { jenis = "LAN"; }
        else if (rb_fo.isSelected()) { jenis = "FO"; }
        else if (rb_console.isSelected()) { jenis = "Console"; }

        String sql = "UPDATE Kabel SET panjang_kabel=?, jenis_kabel=?, tipe_kabel=? WHERE id_kabel=?";
    
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
        pst.setString(1, txt_pjgkabel.getText());
        pst.setString(2, jenis);
        pst.setString(3, txt_tpkabel.getText());
        pst.setString(4, txt_id.getText());
    
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
        datatable();
        reset_form();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:                                      
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kabel");
    model.addColumn("Nama Kabel");
    model.addColumn("Jenis");
    model.addColumn("Dimensi");

    try {
        // Query menggunakan LIKE untuk mencari kata yang mengandung input dari txt_cari
        String sql = "SELECT * FROM Kabel WHERE panjang_kabel LIKE '%" + txt_cari.getText() + "%' "
                   + "OR id_kabel LIKE '%" + txt_cari.getText() + "%'";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_kabel.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_tpkabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tpkabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tpkabelActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kabel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_console;
    private javax.swing.JRadioButton rb_fo;
    private javax.swing.JRadioButton rb_lan;
    private javax.swing.JTable tbl_kabel;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_pjgkabel;
    private javax.swing.JTextField txt_tpkabel;
    // End of variables declaration//GEN-END:variables
}
