/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi; 
/**
 *
 * @author dhamara
 */
public class popup_perangkat extends javax.swing.JDialog {
    public transaksi trx;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(popup_perangkat.class.getName());

    /**
     * Creates new form popup_perangkat
     */
    public popup_perangkat(java.awt.Frame parent, boolean modal, transaksi trx_masuk) {
        super(parent, modal);
        initComponents();
        this.trx = trx_masuk;
        datatable();
    }
    
private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("SN Perangkat");
    model.addColumn("Nama");
    model.addColumn("Jenis");
    model.addColumn("Dimensi"); // Saya sesuaikan jadi 4 kolom saja

    try {
        String cari = txt_cari_popup.getText();
        koneksi koneksi = new koneksi(); 
        java.sql.Connection conn = koneksi.connect();
        
        // Query diperbaiki: hapus 'stok', ganti 'dimensi' jadi 'Dimensi' (sesuai gambar)
        String sql = "SELECT sn_perangkat, nama_perangkat, jenis_perangkat, Dimensi FROM Perangkat " +
                     "WHERE sn_perangkat LIKE '%"+cari+"%' OR nama_perangkat LIKE '%"+cari+"%'";
        
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{
                res.getString(1), // sn_perangkat
                res.getString(2), // nama_perangkat
                res.getString(3), // jenis_perangkat
                res.getString(4)  // Dimensi
            });
        }
        tbl_perangkat_popup.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Gagal load data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cari_popup = new javax.swing.JTextField();
        btn_cari_popup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_perangkat_popup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_cari_popup.setText("Cari");
        btn_cari_popup.addActionListener(this::btn_cari_popupActionPerformed);

        tbl_perangkat_popup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_perangkat_popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_perangkat_popupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_perangkat_popup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cari_popup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cari_popup)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_popup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cari_popupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_popupActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_btn_cari_popupActionPerformed

    private void tbl_perangkat_popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_perangkat_popupMouseClicked
        // TODO add your handling code here:
      int row = tbl_perangkat_popup.getSelectedRow();
    
    // Gunakan view.transaksi (sesuaikan 'view' dengan nama package kamu)
    ((view.transaksi)trx).txt_sn_perangkat.setText(tbl_perangkat_popup.getValueAt(row, 0).toString());
    ((view.transaksi)trx).txt_nama_perangkat.setText(tbl_perangkat_popup.getValueAt(row, 1).toString());
    ((view.transaksi)trx).txt_dimensi.setText(tbl_perangkat_popup.getValueAt(row, 2).toString());
    
    this.dispose();
    }//GEN-LAST:event_tbl_perangkat_popupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                popup_perangkat dialog = new popup_perangkat(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_popup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_perangkat_popup;
    private javax.swing.JTextField txt_cari_popup;
    // End of variables declaration//GEN-END:variables
}
