/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi; 
/**
 *
 * @author dhamara
 */
public class popup_kabel extends javax.swing.JDialog {
    public transaksi trx;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(popup_kabel.class.getName());

    /**
     * Creates new form popup_kabel
     */
    public popup_kabel(java.awt.Frame parent, boolean modal, transaksi trx_masuk) {
        super(parent, modal);
        initComponents();
        this.trx = trx_masuk;
        datatable();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kabel");
    model.addColumn("Tipe Kabel");
    model.addColumn("Panjang (m)");

    try {
        String cari = txt_cari_popup.getText();
        koneksi koneksi = new koneksi(); 
        java.sql.Connection conn = koneksi.connect();
        String sql = "SELECT id_kabel, tipe_kabel, panjang_kabel FROM Kabel " +
                     "WHERE tipe_kabel LIKE '%"+cari+"%' OR id_kabel LIKE '%"+cari+"%'";
        
        java.sql.ResultSet res = conn.createStatement().executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3)});
        }
        tbl_kabel_popup.setModel(model);
    } catch (Exception e) {
        System.out.println("Error Kabel: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cari_popup = new javax.swing.JTextField();
        btn_cari_popup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kabel_popup = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_cari_popup.setText("Cari");
        btn_cari_popup.addActionListener(this::btn_cari_popupActionPerformed);

        tbl_kabel_popup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kabel_popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kabel_popupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kabel_popup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_cari_popup, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cari_popup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_popup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_popup))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_kabel_popupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kabel_popupMouseClicked
        // TODO add your handling code here:
        int row = tbl_kabel_popup.getSelectedRow();
    
    // Gunakan (transaksi) untuk memberi tahu Java tipe datanya
    ((transaksi)trx).txt_id_kabel.setText(tbl_kabel_popup.getValueAt(row, 0).toString());
    ((transaksi)trx).txt_tipe_kabel.setText(tbl_kabel_popup.getValueAt(row, 1).toString());
    ((transaksi)trx).txt_panjang_kabel.setText(tbl_kabel_popup.getValueAt(row, 2).toString());
    
    this.dispose();
    }//GEN-LAST:event_tbl_kabel_popupMouseClicked

    private void btn_cari_popupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_popupActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_btn_cari_popupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                popup_kabel dialog = new popup_kabel(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_popup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_kabel_popup;
    private javax.swing.JTextField txt_cari_popup;
    // End of variables declaration//GEN-END:variables
}
