/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 

/**
 *
 * @author dhamara
 */
public class supplier extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(supplier.class.getName());

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        datatable();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Perangkat");
    model.addColumn("Nama Supplier");
    model.addColumn("Alamat Supplier");
    model.addColumn("NO Telepon");
    model.addColumn("Nama PIC");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery("SELECT * FROM Supplier");
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4),
                res.getString(5)
            });
        }
        tbl_supplier.setModel(model); 
    } catch (Exception e) {
        System.out.println("Gagal load data: " + e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnm_supplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtid_supplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtalamat_supplier = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtno_telepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnm_pic = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supplier = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENGELOLAAN DATA SUPPLIER");

        jLabel2.setText("ID Supplier");

        jLabel3.setText("Nama Supplier");

        txtid_supplier.addActionListener(this::txtid_supplierActionPerformed);

        jLabel4.setText("Alamat Supplier");

        jLabel5.setText("No Telepon");

        jLabel6.setText("nama PIC");

        txtnm_pic.addActionListener(this::txtnm_picActionPerformed);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_remove.setText("Remove");
        btn_remove.addActionListener(this::btn_removeActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        jLabel7.setText("Cari Data Supplier?");

        btn_cari.setText("cari");
        btn_cari.addActionListener(this::btn_cariActionPerformed);

        tbl_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_supplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_supplier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cari))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtnm_pic, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(txtno_telepon)
                            .addComponent(txtalamat_supplier)
                            .addComponent(txtnm_supplier)
                            .addComponent(txtid_supplier))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnm_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamat_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtno_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnm_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_remove)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
     try {
        String sql = "UPDATE Supplier SET nama_supplier=?, alamat_supplier=?, no_telepon=?, nama_PIC=? WHERE id_supplier=?";
    
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
        // Mengisi parameter sesuai urutan tanda tanya (?) di atas
        pst.setString(1, txtnm_supplier.getText());
        pst.setString(2, txtalamat_supplier.getText());
        pst.setString(3, txtno_telepon.getText());
        pst.setString(4, txtnm_pic.getText());
        pst.setString(5, txtid_supplier.getText()); 
    
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Supplier Berhasil Diubah");
        
        datatable();    // Memanggil fungsi tampil data agar tabel refresh
        reset_form();   // Memanggil fungsi kosongkan form agar inputan bersih
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Edit Data Supplier: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_editActionPerformed

    private void txtnm_picActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm_picActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm_picActionPerformed
    private void reset_form() {
    txtid_supplier.setText("");
    txtnm_supplier.setText("");
    txtalamat_supplier.setText("");
    txtno_telepon.setText("");
    txtnm_pic.setText("");
    // Kembalikan ID agar bisa diisi lagi
    txtid_supplier.setEditable(true);
    txtid_supplier.requestFocus();
}
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:{
    try {
        String sql = "INSERT INTO Supplier VALUES ('" + txtid_supplier.getText() + "','" 
                     + txtnm_supplier.getText() + "','" + txtalamat_supplier.getText() + "','" 
                     + txtno_telepon.getText() + "','" + txtnm_pic.getText() + "')";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Data Supplier Berhasil Disimpan");
        datatable();
        reset_form();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Simpan Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txtid_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_supplierActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        reset_form();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
            String sql = "DELETE FROM Supplier WHERE id_supplier = '" + txtid_supplier.getText() + "'";
            java.sql.Connection conn = new koneksi.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            datatable();   // Refresh tabel
            reset_form();  // Kosongkan form
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal Hapus: " + e.getMessage());
            }
         }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here: 
        int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah anda yakin ingin keluar dari Pengelolaan Data Supplier?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION);
    
    // Jika user klik tombol YES
    if (confirm == JOptionPane.YES_OPTION) {
        dispose(); // Menutup form Supplier saja
    }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Perangkat");
    model.addColumn("Nama Supplier");
    model.addColumn("Alamat Supplier");
    model.addColumn("No Telepon");
    model.addColumn("Nama PIC");

    try {
        // Query menggunakan LIKE untuk mencari kata yang mengandung input dari txt_cari
        String sql = "SELECT * FROM Supplier WHERE nama_supplier LIKE '%" + txtcari.getText() + "%' "
                   + "OR id_supplier LIKE '%" + txtcari.getText() + "%'";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_supplier.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pencarian Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tbl_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_supplierMouseClicked
        // TODO add your handling code here:
   
    int baris = tbl_supplier.getSelectedRow();
  
    txtid_supplier.setText(tbl_supplier.getValueAt(baris, 0).toString());
    txtnm_supplier.setText(tbl_supplier.getValueAt(baris, 1).toString());
    txtalamat_supplier.setText(tbl_supplier.getValueAt(baris, 2).toString());
    txtno_telepon.setText(tbl_supplier.getValueAt(baris, 3).toString());
    txtnm_pic.setText(tbl_supplier.getValueAt(baris, 4).toString());
    
    // 3. Kunci ID Supplier agar tidak bisa diubah saat proses edit
    txtid_supplier.setEditable(false);
    }//GEN-LAST:event_tbl_supplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new supplier().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_supplier;
    private javax.swing.JTextField txtalamat_supplier;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid_supplier;
    private javax.swing.JTextField txtnm_pic;
    private javax.swing.JTextField txtnm_supplier;
    private javax.swing.JTextField txtno_telepon;
    // End of variables declaration//GEN-END:variables
}
