/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane; 
/**
 *
 * @author dhamara
 */
public class teknisi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(teknisi.class.getName());

    /**
     * Creates new form teknisi
     */
    public teknisi() {
        initComponents();
        datatable();
    }
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIK Pegawai");
    model.addColumn("Nama Pegawai");
    model.addColumn("Jabatan");
    model.addColumn("Departemen");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery("SELECT * FROM Teknisi");
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1), 
                res.getString(2), 
                res.getString(3), 
                res.getString(4)
            });
        }
        tbl_teknisi.setModel(model); 
    } catch (Exception e) {
        System.out.println("Gagal load data: " + e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnm_pegawai = new javax.swing.JTextField();
        txtnik_pegawai = new javax.swing.JTextField();
        txtdepartemen = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        cmb_jabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_teknisi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENGELOLAAN DATA TEKNISI");

        jLabel2.setText("Nik Pegawai");

        jLabel3.setText("Nama Pegawai");

        jLabel4.setText("Jabatan");

        jLabel5.setText("Departemen");

        txtnik_pegawai.addActionListener(this::txtnik_pegawaiActionPerformed);

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        btn_remove.setText("Remove");
        btn_remove.addActionListener(this::btn_removeActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        jLabel7.setText("Cari Data Teknisi?");

        btn_cari.setText("Cari");
        btn_cari.addActionListener(this::btn_cariActionPerformed);

        cmb_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT Support", "Network Engineer", "Network Operation Centers", "Field Engineer", "Customer Care" }));

        tbl_teknisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_teknisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_teknisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_teknisi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnik_pegawai)
                                    .addComponent(txtnm_pegawai)
                                    .addComponent(txtdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_cari))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnik_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnm_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdepartemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_edit)
                    .addComponent(btn_remove)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        reset_form();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
         try {
        String sql = "UPDATE Teknisi SET nama_pegawai=?, jabatan=?, departemen=? WHERE nik_pegawai=?";
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, txtnm_pegawai.getText());
        pst.setString(2, cmb_jabatan.getSelectedItem().toString());
        pst.setString(3, txtdepartemen.getText());
        pst.setString(4, txtnik_pegawai.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Lokasi Berhasil Diupdate");
        datatable();
        reset_form();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
          int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah anda yakin ingin keluar dari Pengelolaan Data Teknisi?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION);
    
    // Jika user klik tombol YES
    if (confirm == JOptionPane.YES_OPTION) {
        dispose(); // Menutup form Location Teknisi saja
    }
    }//GEN-LAST:event_btn_keluarActionPerformed
    private void reset_form() {
    txtnik_pegawai.setText("");
    txtnm_pegawai.setText("");
    cmb_jabatan.setSelectedIndex(0);
    txtdepartemen.setText("");
    
    txtnik_pegawai.setEditable(true);
    txtnik_pegawai.requestFocus();
    }
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        String jabatan = cmb_jabatan.getSelectedItem().toString();
        try {
        String sql = "INSERT INTO Teknisi VALUES ('" + txtnik_pegawai.getText() + "','" 
                     + txtnm_pegawai.getText() + "','"  + jabatan + "','" 
                     + txtdepartemen.getText() + "')";;
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Data Teknisi Berhasil Disimpan");
        datatable();
        reset_form();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Simpan Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txtnik_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnik_pegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnik_pegawaiActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(null, "Hapus data Teknisi ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // 2. Query DELETE untuk tabel location_rack
            String sql = "DELETE FROM Teknisi WHERE nik_pegawai = '" + txtnik_pegawai.getText() + "'";
            
            java.sql.Connection conn = new koneksi.koneksi().connect();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            // 3. Notifikasi sukses
            JOptionPane.showMessageDialog(null, "Data Teknisi Berhasil Dihapus");
            
            // 4. Refresh Tabel dan Bersihkan Form
            datatable();   
            reset_form();  
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Hapus Teknisi: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK Pegawai");
        model.addColumn("Nama Pegawai");
        model.addColumn("Jabatan");
        model.addColumn("Departemen");

    try {
        // Ambil kata kunci dari textfield cari
        String cari = txtcari.getText();
        
        // Query SQL dengan klausa LIKE untuk mencari berdasarkan Nama Rak atau ID
        String sql = "SELECT * FROM Teknisi WHERE nik_pegawai LIKE '%" + cari + "%' "
                   + "OR nama_rack LIKE '%" + cari + "%'";
        
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4)
            });
        }
        tbl_teknisi.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Pencarian Gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tbl_teknisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_teknisiMouseClicked
        // TODO add your handling code here:
        int baris = tbl_teknisi.getSelectedRow();
        txtnik_pegawai.setText(tbl_teknisi.getValueAt(baris, 0).toString());
        txtnm_pegawai.setText(tbl_teknisi.getValueAt(baris, 1).toString());
    
        // Set item Combo Box berdasarkan data tabel
        String jabatan_terpilih = tbl_teknisi.getValueAt(baris, 2).toString();
        cmb_jabatan.setSelectedItem(jabatan_terpilih);
    
        txtdepartemen.setText(tbl_teknisi.getValueAt(baris, 3).toString());
        txtnik_pegawai.setEditable(false); // Kunci ID Lokasi
    }//GEN-LAST:event_tbl_teknisiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new teknisi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_jabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_teknisi;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtdepartemen;
    private javax.swing.JTextField txtnik_pegawai;
    private javax.swing.JTextField txtnm_pegawai;
    // End of variables declaration//GEN-END:variables
}
