/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement; // Tambahkan ini untuk Submit/Edit
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat; // Untuk format tanggal transaksi
import com.toedter.calendar.JDateChooser; 
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author dhamara
 */
public class transaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transaksi.class.getName());

    /**
     * Creates new form transaksi
     */
    
    public transaksi(String userLogin) {
    initComponents();
    datatable();
    autonumber();
    txt_admin.setText(userLogin);
    txt_admin.setEditable(false);
    }
    public transaksi() {
        initComponents();
        datatable();
        autonumber();
    }
    
    private void datatable() {
    DefaultTableModel model = new DefaultTableModel();
    // 1. Tambah kolom baru di sini biar tabelnya makin lebar dan detail
    model.addColumn("ID Transaksi");
    model.addColumn("Tanggal");
    model.addColumn("ID Barang"); 
    model.addColumn("Jenis");
    model.addColumn("Jumlah");
    model.addColumn("Supplier"); // Kolom Baru
    model.addColumn("Client");   // Kolom Baru
    model.addColumn("Teknisi");  // Kolom Baru
    model.addColumn("Admin");
    
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        
        // Ambil semua data dari tabel Transaksi, urutkan dari yang paling baru
        String sql = "SELECT * FROM Transaksi ORDER BY id_transaksi DESC";
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            // Logika gabungan: Kalau sn_perangkat kosong, ambil id_kabel
            String idBarang = res.getString("sn_perangkat");
            if (idBarang == null || idBarang.isEmpty() || idBarang.equals("")) {
                idBarang = res.getString("id_kabel");
            }

            // Memastikan data string kosong/null diubah jadi "-" biar rapi di tabel
            String supplier = res.getString("id_supplier");
            if (supplier == null || supplier.isEmpty()) supplier = "-";
            
            String client = res.getString("id_client");
            if (client == null || client.isEmpty()) client = "-";
            
            String teknisi = res.getString("nik_pegawai");
            if (teknisi == null || teknisi.isEmpty()) teknisi = "-";

            // 2. Masukkan semua data ke dalam baris tabel (URUTAN HARUS SAMA DENGAN ADDCOLUMN DI ATAS!)
            model.addRow(new Object[]{
                res.getString("id_transaksi"),
                res.getString("tgl_transaksi"), 
                idBarang, 
                res.getString("jenis_transaksi"),
                res.getString("jumlah"),
                supplier, // Data Supplier masuk
                client, // Data Client masuk
                teknisi, // Data NIK Teknisi masuk
                res.getString("username") // Ini kolom admin di DB lu
            });
        }
        tbl_transaksi.setModel(model); 
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal load data tabel: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_id_transaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jd_tgl_transaksi = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_cari_perangkat = new javax.swing.JButton();
        txt_id_kabel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_nama_perusahaan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_dimensi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_jml_perangkat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_cari_kabel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_panjang_kabel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tipe_kabel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_jml_kabel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_id_supplier = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_ket_kabel = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_ket_perangkat = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        cmb_jenis_transaksi = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txt_sn_perangkat = new javax.swing.JTextField();
        btn_cari_teknisi = new javax.swing.JButton();
        txt_nama_perangkat = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_id_client = new javax.swing.JTextField();
        btn_cari_client = new javax.swing.JButton();
        txt_nama_supplier = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_admin = new javax.swing.JTextField();
        btn_reset = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txt_cari_transaksi = new javax.swing.JTextField();
        btn_cari_tabel = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_nik_pegawai = new javax.swing.JTextField();
        btn_cari_supplier1 = new javax.swing.JButton();
        txt_nama_pegawai = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Data Hasil Transaksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 27, -1, -1));

        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 84, -1, -1));

        txt_id_transaksi.addActionListener(this::txt_id_transaksiActionPerformed);
        getContentPane().add(txt_id_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 107, 158, -1));

        jLabel3.setText("Tanggal Transaksi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 84, -1, -1));
        getContentPane().add(jd_tgl_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 107, 158, -1));

        jLabel4.setText("Jenis Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 84, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setText("Data Kabel");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 175, -1, -1));

        jLabel6.setText("SN Perangkat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 206, -1, -1));

        btn_cari_perangkat.setText("Cari");
        btn_cari_perangkat.addActionListener(this::btn_cari_perangkatActionPerformed);
        getContentPane().add(btn_cari_perangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 203, -1, -1));
        getContentPane().add(txt_id_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 203, 100, -1));

        jLabel7.setText("Panjang Kabel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 247, -1, -1));
        getContentPane().add(txt_nama_perusahaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 190, -1));

        jLabel8.setText("Dimensi");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 288, -1, -1));
        getContentPane().add(txt_dimensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 285, 190, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel9.setText("Data Perangkat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 175, -1, -1));

        jLabel10.setText("Jumlah");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 329, -1, -1));
        getContentPane().add(txt_jml_perangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 326, 190, -1));

        jLabel11.setText("ID Kabel");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 206, -1, -1));

        btn_cari_kabel.setText("Cari");
        btn_cari_kabel.addActionListener(this::btn_cari_kabelActionPerformed);
        getContentPane().add(btn_cari_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        jLabel12.setText("Nama Perangkat");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 247, -1, -1));
        getContentPane().add(txt_panjang_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 244, 193, -1));

        jLabel15.setText("Tipe Kabel");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 285, -1, -1));
        getContentPane().add(txt_tipe_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 285, 193, -1));

        jLabel16.setText("Jumlah");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 323, -1, -1));
        getContentPane().add(txt_jml_kabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 320, 193, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel17.setText("Data Teknisi");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));
        getContentPane().add(txt_id_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 120, -1));

        jLabel18.setText("Keterangan");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 367, -1, -1));

        ta_ket_kabel.setColumns(20);
        ta_ket_kabel.setRows(5);
        jScrollPane1.setViewportView(ta_ket_kabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 367, 190, 81));

        jLabel19.setText("Keterangan");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 367, -1, -1));

        ta_ket_perangkat.setColumns(20);
        ta_ket_perangkat.setRows(5);
        jScrollPane2.setViewportView(ta_ket_perangkat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 367, 190, 81));

        jLabel20.setText("ID Supplier");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 524, -1, -1));

        cmb_jenis_transaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barang Masuk", "Barang Keluar" }));
        getContentPane().add(cmb_jenis_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 107, 158, -1));

        jLabel21.setText("Nama Supplier");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 570, 100, -1));
        getContentPane().add(txt_sn_perangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 203, 100, -1));

        btn_cari_teknisi.setText("Cari");
        btn_cari_teknisi.addActionListener(this::btn_cari_teknisiActionPerformed);
        getContentPane().add(btn_cari_teknisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, -1, -1));
        getContentPane().add(txt_nama_perangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 244, 190, -1));

        jLabel22.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel22.setText("Data Supplier");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 493, -1, -1));

        jLabel23.setText("NIK Pegawai");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        jLabel24.setText("Nama Pegawai");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));
        getContentPane().add(txt_id_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 100, -1));

        btn_cari_client.setText("Cari");
        btn_cari_client.addActionListener(this::btn_cari_clientActionPerformed);
        getContentPane().add(btn_cari_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));
        getContentPane().add(txt_nama_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 220, -1));

        jLabel25.setText("Administrator");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 84, -1, -1));

        txt_admin.addActionListener(this::txt_adminActionPerformed);
        getContentPane().add(txt_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 107, 218, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(this::btn_resetActionPerformed);
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, 170, -1));

        btn_submit.setText("Submit");
        btn_submit.addActionListener(this::btn_submitActionPerformed);
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 170, -1));

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, 170, -1));

        btn_cetak.setText("Cetak");
        btn_cetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cetakMouseClicked(evt);
            }
        });
        btn_cetak.addActionListener(this::btn_cetakActionPerformed);
        getContentPane().add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 690, 170, -1));

        jLabel26.setText("Cari Data Transaksi?");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, -1, -1));
        getContentPane().add(txt_cari_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, 150, -1));

        btn_cari_tabel.setText("cari");
        getContentPane().add(btn_cari_tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 770, -1, -1));

        jLabel27.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel27.setText("Data Client");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        jLabel28.setText("ID Client");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        jLabel30.setText("Nama Perusahaan");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));
        getContentPane().add(txt_nik_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 130, -1));

        btn_cari_supplier1.setText("Cari");
        btn_cari_supplier1.addActionListener(this::btn_cari_supplier1ActionPerformed);
        getContentPane().add(btn_cari_supplier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 521, -1, -1));
        getContentPane().add(txt_nama_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 690, 220, -1));

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane3.setViewportView(tbl_transaksi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 850, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_transaksiActionPerformed

    private void btn_cari_kabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_kabelActionPerformed
        // TODO add your handling code here:
    popup_kabel pk = new popup_kabel(this, true, this); 
    pk.setVisible(true);
    }//GEN-LAST:event_btn_cari_kabelActionPerformed

    private void btn_cari_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_clientActionPerformed
        // TODO add your handling code here:
        popup_client pc = new popup_client(this, true, this); 
        pc.setVisible(true);
    }//GEN-LAST:event_btn_cari_clientActionPerformed

    private void txt_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_adminActionPerformed
    
    private void reset_form() {
    // Data Utama
    txt_id_transaksi.setText("");
    jd_tgl_transaksi.setDate(new java.util.Date()); // Set ke tanggal hari ini
    cmb_jenis_transaksi.setSelectedIndex(0); // Balik ke "Barang Masuk"
    
    // Data Perangkat
    txt_sn_perangkat.setText("");
    txt_nama_perangkat.setText("");
    txt_dimensi.setText("");
    txt_jml_perangkat.setText("");
    ta_ket_perangkat.setText("");
    
    // Data Kabel
    txt_id_kabel.setText("");
    txt_panjang_kabel.setText("");
    txt_tipe_kabel.setText("");
    txt_jml_kabel.setText("");
    ta_ket_kabel.setText("");
    
    // Data Supplier & Client
    txt_id_supplier.setText("");
    txt_nama_supplier.setText("");
    txt_id_client.setText("");
    txt_nama_perusahaan.setText("");
    
    // Kembalikan Fokus ke ID Transaksi atau SN
    txt_id_transaksi.requestFocus();
    
    // Panggil datatable lagi supaya pencarian ter-reset
    datatable();
    autonumber();
    
    txt_sn_perangkat.requestFocus();
}
    
    private void autonumber() {
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        java.sql.Statement stm = conn.createStatement();
        String sql = "SELECT * FROM Transaksi ORDER BY id_transaksi DESC";
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        if (res.next()) {
            String NoTrx = res.getString("id_transaksi").substring(3);
            String AN = "" + (Integer.parseInt(NoTrx) + 1);
            String Nol = "";

            if(AN.length()==1) {Nol = "000";}
            else if(AN.length()==2) {Nol = "00";}
            else if(AN.length()==3) {Nol = "0";}
            else if(AN.length()==4) {Nol = "";}

            txt_id_transaksi.setText("TRX" + Nol + AN);
        } else {
            txt_id_transaksi.setText("TRX0001");
        }
        txt_id_transaksi.setEditable(false); // Kunci agar tidak diedit manual
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Auto Number Gagal: " + e.getMessage());
    }
    }
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:                                                                               
    try {
        java.sql.Connection conn = new koneksi.koneksi().connect();
        
        // 1. Ambil Data Header
        String idTrx    = txt_id_transaksi.getText();
        String jenisTrx = cmb_jenis_transaksi.getSelectedItem().toString();
        String admin    = txt_admin.getText();
        
        // Fix Tanggal agar formatnya masuk yyyy-MM-dd ke MySQL
        String tgl = "";
        if (jd_tgl_transaksi.getDate() != null) {
            java.text.SimpleDateFormat fm = new java.text.SimpleDateFormat("yyyy-MM-dd");
            tgl = fm.format(jd_tgl_transaksi.getDate());
        } else {
            JOptionPane.showMessageDialog(null, "Tanggal Transaksi belum diisi!");
            return;
        }
        
        // 2. Ambil Semua Nilai dari Form
        String snPerangkat = txt_sn_perangkat.getText();
        String idKabel     = txt_id_kabel.getText();
        String idSup       = txt_id_supplier.getText();
        String idCli       = txt_id_client.getText();
        String nikPeg      = txt_nik_pegawai.getText(); 
        
        // Ambil jumlah secara fleksibel
        int jml = 0;
        if (!txt_jml_perangkat.getText().isEmpty()) {
            jml = Integer.parseInt(txt_jml_perangkat.getText());
        } else if (!txt_jml_kabel.getText().isEmpty()) {
            jml = Integer.parseInt(txt_jml_kabel.getText());
        }
        
        String ket = ta_ket_perangkat.getText().isEmpty() ? ta_ket_kabel.getText() : ta_ket_perangkat.getText();

        // 3. JURUS SAKTI: Matikan pengecekan Foreign Key biar MySQL gak bawel soal tabel login/Register
        java.sql.Statement stmtBypass = conn.createStatement();
        stmtBypass.execute("SET FOREIGN_KEY_CHECKS=0");

        // 4. Eksekusi Query INSERT 11 Kolom
        String sql = "INSERT INTO Transaksi VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idTrx);
        pst.setString(2, tgl);
        pst.setString(3, jenisTrx);
        pst.setString(4, snPerangkat); 
        pst.setString(5, idKabel);     
        pst.setString(6, idSup);       
        pst.setString(7, idCli);       
        pst.setString(8, nikPeg);      
        pst.setString(9, admin); // dhamara345 masuk ke sini dengan aman!
        pst.setInt(10, jml);
        pst.setString(11, ket);
        pst.execute();

        // 5. Hidupkan kembali pengecekan Foreign Key demi keamanan database setelah data masuk
        stmtBypass.execute("SET FOREIGN_KEY_CHECKS=1");

        // Pesan Sukses
        JOptionPane.showMessageDialog(null, "Transaksi Berhasil Disimpan!");
        
        // Refresh tabel dan kosongkan form kembali
        datatable();
        reset_form();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error Submit: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset_form();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_cari_perangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_perangkatActionPerformed
        // TODO add your handling code here:
    popup_perangkat pp = new popup_perangkat(this, true, this);
    pp.trx = this; // JANGAN SAMPAI LUPA BARIS INI
    pp.setVisible(true);
    }//GEN-LAST:event_btn_cari_perangkatActionPerformed

    private void btn_cari_teknisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_teknisiActionPerformed
        // TODO add your handling code here:
         popup_teknisi pt = new popup_teknisi(this, true, this);
        pt.trx = this; // JANGAN SAMPAI LUPA BARIS INI
        pt.setVisible(true);
    }//GEN-LAST:event_btn_cari_teknisiActionPerformed

    private void btn_cari_supplier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_supplier1ActionPerformed
        // TODO add your handling code here:
        popup_supplier ps = new popup_supplier(this, true, this); 
        ps.trx = this;
        ps.setVisible(true);
    }//GEN-LAST:event_btn_cari_supplier1ActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin kembali ke Menu Utama?", "Peringatan", dialogBtn);
    
        if (dialogResult == JOptionPane.YES_OPTION) {
        this.dispose(); // Menutup form transaksi saja dan balik ke menu utama yang masih kebuka
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cetakMouseClicked
        // TODO add your handling code here:
        int baris = tbl_transaksi.getSelectedRow();
        // Ambil data kolom ke-0 (ID Transaksi) dari baris yang diklik
        String id_klik = tbl_transaksi.getValueAt(baris, 0).toString(); 
        txt_id_transaksi.setText(id_klik);
    }//GEN-LAST:event_btn_cetakMouseClicked

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Ambil ID dari baris tabel yang sedang diklik secara langsung biar akurat!
        int baris = tbl_transaksi.getSelectedRow();
        if (baris == -1) {
            JOptionPane.showMessageDialog(null, "Silakan klik/pilih salah satu baris data di tabel bawah dulu, bro!");
            return;
        }
        
        // Mengambil nilai ID Transaksi langsung dari kolom ke-0 tabel yang lu klik
        String idTarget = tbl_transaksi.getValueAt(baris, 0).toString();
        
        // 2. Jalur file report lu
        String jrxmlPath = "src/report/report_transaksi.jrxml";
        String jasperPath = "src/report/report_transaksi.jasper";
        
        // Compile otomatis
        net.sf.jasperreports.engine.JasperCompileManager.compileReportToFile(jrxmlPath, jasperPath);
        
        // 3. Masukkan ID Target tadi ke dalam parameter database
        java.util.HashMap<String, Object> parameters = new java.util.HashMap<>();
        parameters.put("id_transaksi", idTarget); // Menembak ID yang lu sorot biru (Misal: TRX0001)
        
        // 4. Hubungkan database dan cetak
        java.sql.Connection conn = new koneksi.koneksi().connect();
        net.sf.jasperreports.engine.JasperPrint print = net.sf.jasperreports.engine.JasperFillManager.fillReport(jasperPath, parameters, conn);
        net.sf.jasperreports.view.JasperViewer.viewReport(print, false); 
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal Mencetak Laporan: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transaksi("Admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_client;
    private javax.swing.JButton btn_cari_kabel;
    private javax.swing.JButton btn_cari_perangkat;
    private javax.swing.JButton btn_cari_supplier1;
    private javax.swing.JButton btn_cari_tabel;
    private javax.swing.JButton btn_cari_teknisi;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_jenis_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jd_tgl_transaksi;
    private javax.swing.JTextArea ta_ket_kabel;
    private javax.swing.JTextArea ta_ket_perangkat;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txt_admin;
    private javax.swing.JTextField txt_cari_transaksi;
    public javax.swing.JTextField txt_dimensi;
    public javax.swing.JTextField txt_id_client;
    public javax.swing.JTextField txt_id_kabel;
    public javax.swing.JTextField txt_id_supplier;
    private javax.swing.JTextField txt_id_transaksi;
    private javax.swing.JTextField txt_jml_kabel;
    private javax.swing.JTextField txt_jml_perangkat;
    public javax.swing.JTextField txt_nama_pegawai;
    public javax.swing.JTextField txt_nama_perangkat;
    public javax.swing.JTextField txt_nama_perusahaan;
    public javax.swing.JTextField txt_nama_supplier;
    public javax.swing.JTextField txt_nik_pegawai;
    public javax.swing.JTextField txt_panjang_kabel;
    public javax.swing.JTextField txt_sn_perangkat;
    public javax.swing.JTextField txt_tipe_kabel;
    // End of variables declaration//GEN-END:variables
}
